<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9Y7KqL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9Y7KqL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS9Y7KqL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS9Y7KqL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS9Y7KqL\App_KernelDevDebugContainer([
    'container.build_hash' => 'S9Y7KqL',
    'container.build_id' => '89385dc3',
    'container.build_time' => 1596728433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9Y7KqL');
